name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH Key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    # 서버의 호스트 키를 known_hosts에 추가
    - name: Add server to known_hosts
      run: ssh-keyscan -H 172.234.80.216 >> ~/.ssh/known_hosts

    - name: Set environment variables
      run: |
        echo "REACT_APP_API_KEY_DEV=${{ secrets.REACT_APP_API_KEY_DEV }}" >> client/.env

    # 서버에 최신 코드 가져오고 PM2로 재시작
    - name: Pull latest code and restart server
      run: |
        ssh -o StrictHostKeyChecking=no root@172.234.80.216 '
          cd /var/www/TheHothaan &&
          git pull origin main &&
          pm2 restart all
        '
