name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH Key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    # 서버의 호스트 키를 known_hosts에 추가
    - name: Add server to known_hosts
      run: ssh-keyscan 172.234.80.216 >> ~/.ssh/known_hosts

    - name: Set environment variables
      run: |
        echo "REACT_APP_API_KEY_DEV=${{ secrets.REACT_APP_API_KEY_DEV }}" >> client/.env

    - name: Install client dependencies
      run: |
        cd client
        npm install

    - name: Install server dependencies
      run: |
        cd server
        npm install

    - name: Install root dependencies
      run: |
        npm install

    - name: Build project
      run: |
        CI=false npm run build

    - name: Deploy client to server
      run: |
        ssh root@172.234.80.216 'rm -rf /var/www/TheHothaan/client/build/*'
        scp -r client/build/* root@172.234.80.216:/var/www/TheHothaan/client/build/

    - name: Deploy server to server
      run: |
        ssh root@172.234.80.216 'rm -rf /var/www/TheHothaan/server/*'
        scp -r server/* root@172.234.80.216:/var/www/TheHothaan/server/

    - name: Restart server process
      run: |
        ssh root@172.234.80.216 'pm2 restart all'
